version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    ports: 
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: repos

#   api:
#     build:
#       context: .
#       dockerfile: api/Dockerfile
#     environment:
#       MYSQL_USER: root
#       MYSQL_ROOT_PASSWORD: supersecret
#       MYSQL_DATABASE: tcp(db:3306)/repos
#     ports:
#       - "1323:1323"
#     volumes:
#       - ./:/go/src/github.com/dvbnrg/Golang-Demo
#     depends_on:
#       - db
#     links:
#       - "db:database"